// DO NOT MODIFY THIS FILE, IT WILL BE OVERRIDE!!!
#ifndef _KENDRYTE_IDE_FLASH_MANGER_OUT_H
#define _KENDRYTE_IDE_FLASH_MANGER_OUT_H

#define _START 0x601000
#define _END 0x602000
#define _SIZE 227

#endif // _KENDRYTE_IDE_FLASH_MANGER_OUT_H

